version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: household-budget-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: household_budget_db
    ports:
      - "6432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d household_budget_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - household-budget-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: household-budget-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@household-budget.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
    ports:
      - "8082:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./scripts/pgadmin-servers.json:/pgadmin4/servers.json
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - household-budget-network

volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local

networks:
  household-budget-network:
    driver: bridge